### ISSUE TITLE
Is the version of the hextrudort in this repo modified from the original hextrudort?

### ISSUE THREAD

**Issue by blindMoe** [Mamsih/VOV0-toolhead-voron-Zero#3]
I have noticed that some of the sizing seems odd on this version of the Hextrudort and am curious if this is a purposeful modification or just an older version of the Hextrudort?  I was planning on printing out the official version of the Hextrudort but did not know if it would need to be modified.

**Comment by Mamsih** [comment]
Yes it's modified versoin for my versoin, if you wanna use the VOV0 tool
you have to print the hextruder which come with it

**Comment by blindMoe** [comment]
It seems like maybe the only part that is modified is the body of the extruder itself, is that true?  I noticed that on the back place, your version has a 1.5mm inset for the bearing but on the Hextrudort it is ~2.2mm which lets the entire bearing sit in further.  The main issue I am having is that the large gear, its shaft and the hob gear on its shaft seem to not fit properly in the housing.  I have tried both a bondtech kit from AliExpress and genuine bond tech parts and am running in to the same binding issues.  Any tips would be greatly appreciated, everything is print and mostly put together and getting this binding issue resolved is the last piece of the puzzle before I can install the extruder.  I am excited to get it going!

**Comment by Mamsih** [comment]
I will double check that for you Sean 👆

**Comment by Mamsih** [comment]
update 27/09/2021 
- add adjustable slot on the backplate for controlling backlash
- more tolerance for MR85ZZ bearing 
- less support needed

**Comment by blindMoe** [comment]
That one feels much smoother!  Very much appreciated! Coffee donation coming your way! ( Feel free to use it for beer )

**Comment by blindMoe** [comment]
Everything looks and works great but I did notice that V2 of the Cover actually fits better on the bearing than V3 does.  So right now I am running with V3 everything but V2 cover and it is buttery smooth!
