### ISSUE TITLE
Missing throughole for Dragon mountpoint

### ISSUE THREAD

**Issue by bbbenji** [Mamsih/VOV0-toolhead-voron-Zero#4]
The mount for the Dragon hotend (left & right) is missing through-holes for mounting the actual hotend itself to the extruder.

In addition, there is a second hole that appears to be unnecessary, marked in my screenshot with a `?`.

Perhaps I am not understanding the assembly process, please explain if that is the case.

![2021-09-28_09-25](https://user-images.githubusercontent.com/1678118/135042287-f12ab93b-3e1d-4007-a474-da4eb354a125.png)

Will you be releasing source files for this toolhead?

**Comment by Mamsih** [comment]
mounting holes fixed
![2_screws_dragon](https://user-images.githubusercontent.com/70104136/135046036-b113edfd-19ce-46cc-818b-474c2c5b8001.PNG)

**Comment by Mamsih** [comment]
the big hole for the m3 heat insert to mount the extruder 
smalles one for 2 screws of 2.5mm mounting for the dragon

**Comment by bbbenji** [comment]
Thank you!

Fixed via: https://github.com/Mamsih/VOV0-toolhead-voron-Zero/commit/07d2be7ad04f2dcbf866388e8baeb7c91f894962
