### ISSUE TITLE
B_VOV0_main_V3.STL overhang

### ISSUE THREAD

**Issue by antgeo** [Mamsih/VOV0-toolhead-voron-Zero#5]
Only a small section of this part sits on the bed. I've attached a screenshot from the slicer

![image](https://user-images.githubusercontent.com/44141/135193315-58a329fb-2064-4e18-9c46-7eb862bc08c3.png)

**Comment by blindMoe** [comment]
I am able to replicate that as well.  You can just drop the model down that tiny bit into the bed to cut off that single layer that causes the lift but I actually flipped the part over 180 degrees and added some manual supports to make it a little cleaner and it worked out really well.

<img width="868" alt="Screen Shot 2021-09-28 at 22 57 17" src="https://user-images.githubusercontent.com/1441164/135211432-fba31b33-66ab-430b-b214-d163073b3696.png">

**Comment by Mamsih** [comment]
Woow sorry I fixed that yesterday, I thought I uploaded the right one, I will upload the right one

**Comment by Mamsih** [comment]
fixed
